# Represents a user of the system
type User {
  userId: String
  firstname: String
  lastname: String
}

type LoggedInDetails {
  isNewUser: Boolean
  loginToken: String
  loggedInUser: User
}

type UserMutations {
  loginUser: LoggedInDetails
  userId: String
  firstname: String
  lastname: String
}