# Represents a user of the system
type User {
  userId: String
  firstName: String
  lastName: String
}

type LoggedInDetails {
  isNewUser: Boolean
  loginToken: String
  loggedInUser: User
  username: String
  password: String
}

type UserMutations {
  loginUser: LoggedInDetails
}