# Represents a user of the system
type User {
  username: String
  password: String
}

type LoggedInDetails {
  isNewUser: Boolean
  loginToken: String
  loggedInUser: User
}

type UserMutations {
  loginUser(username: String, password: String): LoggedInDetails
  registerUser(username: String, password: String): LoggedInDetails
  resetPassword(username: String): LoggedInDetails
}